In [1]:
import pandas as pd
import numpy as np
import time

from utils import BatchGenerator, batch_balance_sampling, read_img
from callbacks import SlackLogger #custom file for callbacks
from models import unet

Using TensorFlow backend.


In [2]:
data = pd.read_pickle("train-data-filelist.pkl")
fms = [read_img(path) for path in data['fissuremask'].values]

In [3]:
counts = []
for f in fms:
    _, c = np.unique(f, return_counts=True)
    c = c.tolist()
    if len(c) < 3:
        c.append(0)
    counts.append(c)

In [4]:
counts = np.array(counts)
print(counts)
means = np.sum(counts,axis=0)/np.sum(counts)
print(means)

[[21573112    25702    23686]
 [13476191    14117     6317]
 [14319347     5225    20552]
 [30698975    34230    14590]
 [54584038    54382    16897]
 [17938915    12972    20258]
 [28241759    35247    11744]
 [17363884    29070     7583]
 [32309485    34093     9622]
 [29984829    35945    14413]
 [35309522    30461     8304]
 [32281286     9179    26555]
 [30431441    37571    14419]
 [27191421    24543    18342]
 [42130951    27000    31196]
 [20673602    25310     7523]
 [23159704    17414     9760]
 [10355186     9992     7697]
 [30141542    40955    11603]
 [31352028    28623    21564]
 [31536878    22303    25944]
 [29525846    35591     9233]
 [35451995    38404    18261]
 [34053457    36989    14359]
 [20743754    10067    20114]
 [47915092    45871    13702]
 [34460988    36434    11899]
 [20845821    23698    10361]
 [40474869    48455    12394]
 [28485883    26075    12642]
 [35134991    37897     5808]
 [37703740    40463     8547]
 [36508274    48984     9512]
 [24611639

In [5]:
weights = 1.0/means
print(weights)

[  1.00153150e+00   7.52326739e+02   5.00137535e+03]
